### ISSUE TITLE
Mathematical inaccurate language

### ISSUE THREAD

**Issue by abbyesmith** [learn-co-curriculum/phase-1-arithmetic-lab#12]
### Canvas Link

https://learning.flatironschool.com/courses/6264/assignments/227910?module_item_id=532042

### Concern

2. Create a variable called random that will generate a random integer greater than 0.

This is the second challenge of the Arithmetic lab. I challenge that the answer that is correct (let random = Math.floor(Math.random() * 10) + 1) does not satisfy this condition.

A random integer greater than 0 is the set of numbers without decimals greater or equal to 1. For example, the value 9,999,999,999 is a random integer greater than 0. The correct answer according to the npm test limits our field of answers to any integer 1 to 10.

**Comment by jlboba** [comment]
Hello, thank you for opening this issue. 

Unfortunately, I can't seem to reproduce this problem. The test for the `random` problem does not limit the field of answers between 1-10. It checks for any number that is not 0, meaning the value 9,999,999,999 should pass as well. 

I ran the test on `const random = Math.floor(Math.random() * 1000000000000) + 1;` and that passed fine for me both locally and on CodeGrade. 

As such, I will close this issue for now. However, if you can provide further detail, such as the code you wrote that did not pass, I'd be happy to take a second look! 

Either way, we appreciate your contribution 💙
