### ISSUE TITLE
concern with being left behind. 

### ISSUE THREAD

**Issue by r0seinvase** [learn-co-curriculum/phase-1-arithmetic-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/4557/assignments/157517?module_item_id=335551

### Concern

The lessons seem to be jam packed with different formulas and functions of variables. But structure is not really shown in practice. It's only on labs where we have to figure it out, but as a visual learner, this really debilitates me.  This is found in nearly everyone of these phase 1 lessons. 

### Suggested Changes

I understand that we must practice code but throwing us out cold doesn't really help.

**Comment by lizbur10** [comment]
Hi @r0seinvase ! Thank you for your feedback - we will take it into consideration when we're making updates to the lesson in this phase. 

One thing to keep in mind is that this material is quite challenging and most students struggle with it at times. It will get better over time. 

However, if you find yourself getting stuck for very long, I suggest that you reach out to your instructor for help, or use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks for contributing to the Flatiron School curriculum 💙
