### ISSUE TITLE
"Order of Operations" could start with "why" or a "problem statement"?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-arithmetic-lab#8]
### Canvas Link

https://learning.flatironschool.com/courses/5185/assignments/179309?module_item_id=396098

### Concern

"Precedence" (Order of Operations) is an important concept that might be implemented differently by different languages. As such, the way the course raises the topic seems abrupt. It lays no groundwork or interest (no problem statement or hook about why we should care) but instead seems "Wham Bam", i.e.:

Order of Operations
JavaScript evaluates compound arithmetic operations by following the standard [order of operations (Links to an external site.)](https://en.wikipedia.org/wiki/Order_of_operations) used in basic math.

Technically, the material is there, and students will figure it out, but "a spoonful of sugar" might help newbies relate better to the concept and follow along with more immediate understanding.

### Suggested Changes

Maybe an initial statement like:

Order of Operations
Suppose you ask JavaScript to compute a statement like this:
2 - 2 % 2 + 2 / 2 ** 2 * 2;
How will JavaScript know which operators to process first? Will it crunch them ("-", "%", "+", etc.) in a left-to-right order (2 - 2, and then 0 % 2, and so on) or does it have a different set of rules?

________
I'm tempted to work in the term "precedence" somehow, but minimizing jargon is also helpful for newbies, so I'm ok with "Order of Operations". :-)

**Comment by lizbur10** [comment]
Hi @brigj1 ! Nice suggestion! Thanks 💙
